FROM alpine:3.7

WORKDIR /app

RUN cat /etc/alpine-release

RUN apk add --no-cache \ 
        php5 \
        php5-cgi \
        php5-cli \
        php5-ctype \
        php5-curl \
        php5-dom \
        php5-iconv \
        php5-json \
        php5-ldap \
        php5-opcache \
        php5-pcntl \
        php5-pdo \
        php5-pdo_mysql \
        php5-pdo_pgsql \
        php5-phar \
        php5-posix \
        php5-xml \
        php5-bcmath \
        php5-zlib \
        php5-gd \
        git \
        icu \
        libpng \
        libjpeg \
        freetype \
        libzip \
        libx11 \
        libxrender-dev \
        fontconfig-dev \
        openssl-dev \
        libcrypto1.0 \
        libssl1.0 \
        ttf-dejavu \
        ttf-freefont \
    && rm -rf /var/cache/* \
    && rm -rf /usr/src

COPY ini/php.ini /usr/local/etc/php/
