FROM php:5-cli-alpine

WORKDIR /app

RUN apk add --no-cache --update --virtual .build-deps \
        autoconf \
        binutils \
        curl-dev \
        freetype-dev \
        g++ \
        gcc \
        icu-dev\
        pcre-dev \
        libcurl \
        libjpeg-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        libxml2-dev \
        make \
        postfix \
        libzip-dev \
    && apk add --no-cache git icu libpng libjpeg freetype libzip \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-configure zip --with-libzip \
    && docker-php-ext-install -j "$(getconf _NPROCESSORS_ONLN)" \
        exif \
        gd \
        intl \
        pdo_mysql \
        soap \
        zip \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/* \
    && rm -rf /usr/src

COPY ini/php.ini /usr/local/etc/php/
