FROM alpine:latest

# Memory limit set to 1024MB as the composer image is based off this. Composer
# uses lots of memory when used in development.
ENV PHP_MEMORY_LIMIT=1024M

WORKDIR /app

RUN apk add \
    php7 \
    php7-cli \
    php7-ctype \
    php7-curl \
    php7-dom \
    php7-iconv \
    php7-json \
    php7-mbstring \
    php7-opcache \
    php7-pdo \
    php7-pdo_mysql \
    php7-phar \
    php7-sodium \
    php7-tokenizer \
    php7-xml \
    php7-xmlwriter \
    && rm -rf /var/cache/apk/*

COPY ini/php.ini /etc/php7/php.ini
COPY bin/entrypoint-slim /bin/docker-entrypoint
COPY bin/configure-php-ini /bin/configure-php-ini

RUN chmod +x /bin/docker-entrypoint
RUN chmod +x /bin/configure-php-ini

ENTRYPOINT ["/bin/docker-entrypoint"]
CMD ["php"]
