FROM xigen/php:cli-composer

RUN chown -Rvf composer: /app

USER composer

RUN composer global require --ignore-platform-reqs phpmd/phpmd sebastian/phpcpd symfony/phpunit-bridge vimeo/psalm xigen.io/phpcs-ruleset

ENTRYPOINT ["/bin/php"]
