FROM php:5-cli-alpine

WORKDIR /app

RUN apk add --no-cache --update --virtual .build-deps \
        autoconf \
        binutils \
        curl-dev \
        freetype-dev \
        g++ \
        gcc \
        icu-dev\
        pcre-dev \
        libcurl \
        libjpeg-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        libxml2-dev \
        make \
        postfix \
        libzip-dev \
        libmemcached-dev \
        libxrender \
        fontconfig \
        libcrypto1.0 \
        openssl \
        ttf-dejavu \
    && apk add --no-cache git icu libpng libjpeg freetype libzip \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-configure zip --with-libzip \
    && docker-php-ext-install -j "$(getconf _NPROCESSORS_ONLN)" \
        bcmath \
        exif \
        gd \
        intl \
        pdo_mysql \
        soap \
        zip \
    && pecl install memcached-2.2.0 \
    && pecl install memcache \
    && echo "extension=memcached.so" >> /usr/local/etc/php/php.ini \
    && echo "extension=memcache.so" >> /usr/local/etc/php/php.ini \
    && apk del .build-deps git \
    && rm -rf /var/cache/* \
    && rm -rf /usr/src

COPY ini/php.ini /usr/local/etc/php/
