FROM alpine:edge

# Memory limit set to 2048M as the composer image is based off this. Composer
# uses lots of memory when used in development.
ENV PHP_MEMORY_LIMIT=2048M

WORKDIR /app

RUN apk add \
    patch \
    php7 \
    php7-cgi \
    php7-cli \
    php7-ctype \
    php7-curl \
    php7-dom \
    php7-iconv \
    php7-json \
    php7-ldap \
    php7-mbstring \
    php7-opcache \
    php7-pcntl \
    php7-pdo \
    php7-pdo_mysql \
    php7-pdo_pgsql \
    php7-pdo_sqlite \
    php7-phar \
    php7-posix \
    php7-sodium \
    php7-simplexml \
    php7-session \
    php7-sqlite3 \
    php7-tokenizer \
    php7-redis \
    php7-xml \
    php7-xmlwriter \
    && rm -rf /var/cache/apk/*

COPY ini/php.ini /etc/php7/php.ini
COPY bin/entrypoint-slim /bin/docker-entrypoint
COPY bin/configure-php-ini /bin/configure-php-ini

RUN chmod +x /bin/docker-entrypoint
RUN chmod +x /bin/configure-php-ini

ENTRYPOINT ["/bin/docker-entrypoint"]
CMD ["php"]
