FROM composer:2 as composer

RUN mkdir /ppm && cd /ppm && composer require symfony/framework-bundle:v4.4.34 && composer config platform.php 7.4 && composer require --ignore-platform-reqs php-pm/php-pm php-pm/httpkernel-adapter

FROM xigen/php:cli-slim

ENV APP_ENV prod
ENV DATABASE_URL ''
ENV PPM_PORT 80
ENV PPM_DEBUG 0
ENV PPM_LOGGING 1
ENV PPM_WORKERS 4
ENV PPM_TTL 0

EXPOSE 80

COPY --from=composer /ppm /ppm

COPY bin/entrypoint-ppm /bin/docker-entrypoint

RUN chmod +x /bin/docker-entrypoint

ENTRYPOINT ["/bin/docker-entrypoint"]
