FROM php:7.2-cli-alpine3.8

WORKDIR /app

RUN apk add --no-cache --virtual .build-deps \
        autoconf \
        binutils \
        curl-dev \
        freetype-dev \
        g++ \
        gcc \
        icu-dev\
        libcurl \
        libjpeg-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        libxml2-dev \
        libzip-dev \
        make \
        postfix \
    && apk add --no-cache git \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j "$(getconf _NPROCESSORS_ONLN)" \
        bcmath \
        exif \
        fileinfo \
        gd \
        ldap \
        opcache \
        pdo_mysql \
        soap \
        redis \
        zip \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/* \
    && rm -rf /usr/src

COPY ini/php.ini /usr/local/etc/php/
