FROM xigen/php:cli-slim

ENV COMPOSER_MEMORY_LIMIT=2048M

ENV PATH="/home/composer/.composer/vendor/bin:${PATH}"

ADD --chown=1000:1000 https://github.com/composer/composer/releases/download/1.8.0/composer.phar /bin/composer

COPY --chown=1000:1000 --from=xigen/keys-server:latest /id_rsa /.ssh/id_rsa

# Install required application dependencies
RUN apk --no-cache --update add openssh-client git \
  && adduser -D -u 1000 composer \
  && chmod +x /bin/composer \
  && chmod 600 /.ssh/id_rsa && eval $(ssh-agent -s) && ssh-add /.ssh/id_rsa

RUN composer global require hirak/prestissimo

ENTRYPOINT ["/bin/composer"]
