FROM php:7.3-fpm-alpine

ENV TZ=Europe/London

WORKDIR /var/www

RUN apk add --no-cache --virtual .build-deps \
    autoconf \
    binutils \
    freetype-dev \
    g++ \
    gcc \
    icu-dev \
    icu-libs \
    libxml2-dev \
    libxslt-dev \
    libjpeg-turbo-dev \
    libzip-dev \
    make \
    libzip-dev \
# =========================================================================== #\
    && apk add --no-cache \
        freetype \
        icu-libs \
        libjpeg-turbo \
        libpng \
        libxml2 \
        libxslt \
        libzip \
        postfix \
        tzdata \
# =========================================================================== #\
    && docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-png-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-configure zip --with-libzip \
    && docker-php-ext-install -j "$(getconf _NPROCESSORS_ONLN)" \
        bcmath \
        exif \
        gd \
        intl \
        opcache \
        mysqli \
        soap \
        sysvsem \
        xsl \
        zip \
        && apk del .build-deps \
        && rm -rf /var/cache/apk/* \
        && rm -rf /usr/src \
# == Setup fallback sessions =============================================== # \
        && mkdir -p /var/www/var/cache/ \
        && chown -Rf 82:82 /var/www/var/cache/ \
        && mkdir -p /var/www/var/sessions/ \
        && chown -Rf 82:82 /var/www/var/sessions/

COPY conf/www.conf /usr/local/etc/php-fpm.d/
COPY ini/php.ini /usr/local/etc/php/
