FROM php:7.4-fpm-alpine

ENV TZ=Europe/London

ENV REDIS_VERSION="5.2.1"

WORKDIR /var/www

RUN curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/${REDIS_VERSION}.tar.gz \
    && tar xfz /tmp/redis.tar.gz \
    && rm -r /tmp/redis.tar.gz \
    && mkdir -p /usr/src/php/ext \
    && mv phpredis-* /usr/src/php/ext/redis \
# =========================================================================== #\
    && apk add --no-cache --virtual .build-deps \
        autoconf \
        binutils \
        freetype-dev \
        g++ \
        gcc \
        icu-dev \
        icu-libs \
        libxml2-dev \
        libxslt-dev \
        libjpeg-turbo-dev \
        libzip-dev \
        make \
        openldap-dev \
        libzip-dev \
# =========================================================================== #\
    && apk add --no-cache \
        freetype \
        icu-libs \
        libjpeg-turbo \
        libpng \
        libxml2 \
        libxslt \
        libzip \
        openldap \
        postfix \
        postgresql \
        tzdata \
# =========================================================================== #\
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j "$(getconf _NPROCESSORS_ONLN)" \
        bcmath \
        exif \
        gd \
        intl \
        ldap \
        opcache \
        pdo_mysql \
        pdo_pgsql \
        redis \
        soap \
        sysvsem \
        xsl \
        zip \
        && apk del .build-deps \
        && rm -rf /var/cache/apk/* \
        && rm -rf /usr/src \
# == Setup fallback sessions =============================================== # \
        && mkdir -p /var/www/var/cache/ \
        && chown -Rf 82:82 /var/www/var/cache/ \
        && mkdir -p /var/www/var/sessions/ \
        && chown -Rf 82:82 /var/www/var/sessions/

COPY conf/www.conf /usr/local/etc/php-fpm.d/
COPY ini/php.ini /usr/local/etc/php/
